[package]
name = "custom-format-tests"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
custom-format = { path = "..", default-features = false }

[features]
compile-time = ["custom-format/compile-time"]
runtime = ["custom-format/runtime"]
default = ["compile-time", "runtime"]
